### PR TITLE
Add support for tofu custom releases URL

### PR DESCRIPTION
**Pull request by rogerxaic**

### CODE REVIEW

**Comment by alfespa17** [comment]
Thank you for your help @rogerxaic I will check this in the following days 👍

**Comment by alfespa17** [comment]
Thank you for your contribution :+1:

**Comment by rogerxaic** [comment]
Thanks @alfespa17!

Sorry I missed the .zip part, MacOS logic apparently doesn't use the release's architecture value, and I hadn't properly tested it.

Is there any way you could trigger a release of this library, please?

**Comment by alfespa17** [comment]
Sure I think a can release some beta so you can test in more detail

**Comment by alfespa17** [comment]
It should be ready in some minutes.

https://github.com/AzBuilder/terraform-spring-boot/releases/tag/0.14.0-beta.1

**Pull request merged**
